os: WMF 5
build: false
environment:
  DeployKey:
    secure: JTKgh7ZbOD951Rg/loeImMQSooAILaNOO+O7zBSqixBGQ5PpbAbdXkRcNhe0ZWpK
install:
- ps: Install-PackageProvider -Name NuGet -Force
before_test:
- ps: Install-Module Pester -Force -SkipPublisherCheck
test_script:
- ps: |
    $filename = ".\TestsResults.xml"
    $results = Invoke-Pester -OutputFormat NUnitXml -OutputFile $filename -PassThru
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $filename))
    if ($results.FailedCount -gt 0) { throw "$($results.FailedCount) tests failed." }
